
image:
  repository: danytgh/docusaurus
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  selector:
    app: docusaurus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <DOMAIN>
    external-dns.alpha.kubernetes.io/ttl: "120"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: <DOMAIN>
      paths:
        - path: "/"
          pathType: Prefix
 
livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000

